# Generated by Django 5.2.6 on 2025-11-09 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('main', 'Main Dish'), ('dessert', 'Dessert'), ('drink', 'Drink'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
